name: fringleapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.2+2002

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pin_code_fields: ^2.3.0+3
  swipe_stack: ^1.0.0
  flutter_swiper: ^1.1.6
  intl: ^0.16.1
  firebase_auth: ^0.15.5+2
  cloud_firestore: ^0.13.4+2
  geolocator: ^5.3.0
  #image_picker: ^0.6.3+4
  image_picker: ^0.6.7+22
  image_cropper: ^1.2.1
  firebase_storage: ^3.1.3
  path_provider:
  cached_network_image: ^2.0.0
  firebase_messaging: ^6.0.13
  flutter_webview_plugin: ^0.3.11
  permission_handler: ^3.0.0
  firebase_database: 3.0.0
  shimmer: ^1.1.1
  url_launcher: ^5.5.0
  mapbox_search_flutter: ^1.0.5
  material_design_icons_flutter: ^4.0.5855
  multi_select_flutter:
  # multi_select_flutter: 4.0.0
  awesome_dialog:
  # awesome_dialog: ^2.1.0
  flutter_cube:
  # flutter_cube: ^0.1.1
  cupertino_icons: ^0.1.2
  shrink_sidemenu: ^1.0.0+3
  liquid_ui: ^1.0.0+9
  syncfusion_flutter_datepicker:
  # syncfusion_flutter_datepicker: ^19.2.47
  clipboard:
  # clipboard: ^0.1.3
  persistent_bottom_nav_bar: ^3.1.0
  flutter_svg: ^0.19.1
  lottie:
  firebase_core: ^0.4.4
  hexcolor:

dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/Icon/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/auth/
    - asset/
    - asset/lottie/
    - asset/cube/shark.obj
    - asset/icons/
    - asset/images/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
